In [1]:
import pandas as pd
import glob
import os
import re

In [2]:
#gather all absolute file paths in raw data folder and place them in a list
def get_files():
    raw_data_path = os.path.abspath(os.path.join(os.getcwd(),".."))
    pattern = os.path.join(raw_data_path,"data","raw","*.xlsx")
    file_lst = glob.glob(pattern)
    return file_lst

In [3]:
#clean and filter data to acceptable parameters
def clean_filter(quarter_df_lst):
    #strip and force lowercase on all, force single "_" between words 
    for q in quarter_df_lst:
        q.columns = q.columns.str.lower()
        q.columns = q.columns.str.strip()
        q.columns = q.columns.str.replace('\\s+', '_', regex=True)
    #filter out any sheets with less than 5 rows
    length_check = [v for v in quarter_df_lst if len(v) > 5]
    #filter out sheets without expected cols
    required_cols = {"start","details","status_text","booking_source","player_count","tee_sheet","date_cancelled"}
    col_check = [v for v in length_check if required_cols.issubset(set(v.columns))]
    #filter out sheets with more than 10% NA values on the start time
    valid_start_time = [v for v in col_check if v["start"].isna().mean() < 0.10]
    final = valid_start_time
    return final
    
#for each file, collect each tab into a dict w/ tab name as key, df of data as value. concat all tabs into a full year df
year_dfs = []
file_lst = get_files()
for file in file_lst:
    quarter_dict = pd.read_excel(file,sheet_name=None)
    quarters = list(quarter_dict.values())
    quarters = clean_filter(quarters)
    if quarters:
        year = pd.concat(quarters)
        year_dfs.append(year)
    else: 
        print(f"'{os.path.basename(file)}': no valid data")

#concat all year dfs into one master df
master_raw = pd.concat(year_dfs,ignore_index=True)

In [4]:
print(master_raw.dtypes)

start             object
details           object
status_text       object
booking_source    object
player_count       int64
tee_sheet         object
date_cancelled    object
dtype: object

In [44]:
#basic cleaning, convert start to datetime, drop booking_source (provides no meaningful input here), rename start to tee_time for clarity
master_df = master_raw.copy()
master_df["start"] = pd.to_datetime(master_df["start"])
master_df.drop(columns=["booking_source"],inplace=True)
master_df.rename(columns={"start":"tee_time"},inplace=True)

In [46]:
#clean time, date, and cost out of details using regex,drop any rows that extract time data to nan
master_df[["book_hr","book_min","am_pm","book_month","book_day","cost_per_group"]] = master_df["details"].str.extract(r"@\s(\d{1,2}):(\d{2})(am|pm|AM|PM|Am|Pm)\s(\d{1,2})\/(\d{1,2})(?:.*?\$(\d+\.\d{2}))?")
master_df.dropna(subset=["book_hr","book_min","am_pm","book_month","book_day"],inplace=True)
master_df[["book_hr","book_min","book_month","book_day"]] = master_df[["book_hr","book_min","book_month","book_day"]].astype(int)
#reformat book time to 24hr to enable cleaning
master_df.loc[master_df["am_pm"] == "pm", "book_hr"] = master_df.loc[master_df["am_pm"] == "pm", "book_hr"]+12
master_df.loc[(master_df["book_hr"] == 12) & (master_df["am_pm"] == "am"), "book_hr"] = 0
# pull year from start, adjust booking time to previous year if booking in dec and tee time in jan
master_df["book_yr"] = master_df["tee_time"].dt.year
master_df.loc[(master_df["tee_time"].dt.month == 1)&(master_df["book_month"] == 12),"book_yr"] = master_df.loc[(master_df["tee_time"].dt.month == 1)&(master_df["book_month"] == 12),"book_yr"]-1
#convert cleaned data to datetime
master_df["booking_time"] = pd.to_datetime(
    {
        "year": master_df["book_yr"],
        "month": master_df["book_month"],
        "day": master_df["book_day"],
        "hour": master_df["book_hr"],
        "minute": master_df["book_min"],
    },
    errors="coerce",
)
# #drop helper date columns to clean up df, reorganize cols
master_df.drop(columns=["book_hr","book_min","am_pm","book_month","book_day", "book_yr"],inplace=True)
master_df = master_df[['tee_time', 'details', 'booking_time', 'status_text', 'player_count', 'tee_sheet',
       'date_cancelled', 'cost_per_group']]


display(master_df)

,tee_time,details,booking_time,status_text,player_count,tee_sheet,date_cancelled,cost_per_group
0,2021-03-14 07:51:00,Reserved using online booking @ 7:00pm 3/7 EST...,2021-03-07 19:00:00,checked in,2,Bethpage Early AM 9 Holes Blue,NaT,124.00
1,2021-03-14 07:51:00,Reserved using online booking @ 9:35pm 3/13 ES...,2021-03-13 21:35:00,checked in,1,Bethpage Early AM 9 Holes Blue,NaT,31.00
2,2021-03-14 08:00:00,Reserved using online booking @ 3:32pm 3/13 ES...,2021-03-13 15:32:00,checked in,2,Bethpage Early AM 9 Holes Blue,NaT,62.00
3,2021-03-14 08:27:00,Reserved using online booking @ 11:19am 3/13 E...,2021-03-13 11:19:00,checked in,4,Bethpage Early AM 9 Holes Blue,NaT,124.00
4,2021-03-14 08:36:00,Reserved using online booking @ 5:42pm 3/13 ES...,2021-03-13 17:42:00,checked in,1,Bethpage Early AM 9 Holes Blue,NaT,93.00
...,...,...,...,...,...,...,...,...
616027,2025-10-21 13:42:00,Reserved using online booking @ 8:00pm 10/14 E...,2025-10-14 20:00:00,NaN,1,Bethpage Blue Course,NaT,15.00
616028,2025-10-21 13:42:00,Reserved using online booking @ 12:32pm 10/15 ...,2025-10-16 00:32:00,NaN,1,Bethpage Blue Course,NaT,23.00
616029,2025-10-21 13:51:00,Reserved using online booking @ 7:02pm 10/14 E...,2025-10-14 19:02:00,NaN,4,Bethpage Blue Course,NaT,92.00
616030,2025-10-21 14:00:00,Reserved using online booking @ 8:55pm 10/14 EDT,2025-10-14 20:55:00,deleted,4,Bethpage Blue Course,2025-10-14 21:21:01,NaN
616031,2025-10-21 14:00:00,Reserved using online booking @ 8:22am 10/15 E...,2025-10-15 08:22:00,NaN,2,Bethpage Blue Course,NaT,46.00

In [34]:
#evaluating scale of bad data to see if it makes sense to delete those records, or apply some further...
#cleaning to allow more numerical analysis
for col in master_df.columns:
    display(master_df[col].value_counts(dropna=False))
    display(master_df.loc[master_df[col].isna()])

tee_time
2024-06-03 06:39:00    47
2024-06-15 17:00:00    45
2024-06-10 06:03:00    40
2024-04-13 08:27:00    39
2024-05-23 07:06:00    39
                       ..
2022-02-16 12:39:00     1
2025-10-21 13:15:00     1
2025-10-21 12:57:00     1
2025-10-21 10:33:00     1
2025-10-21 10:24:00     1
Name: count, Length: 117823, dtype: int64

Empty DataFrame
Columns: [tee_time, details, status_text, player_count, tee_sheet, date_cancelled, book_hr, book_min, am_pm, book_month, book_day, cost_per_group, book_yr, booking_time]
Index: []

details
Reserved using online booking @ 7:00pm 6/27 EDT Original amount due at course: 4 Players for $192.00                                 266
Reserved using online booking @ 7:00pm 5/30 EDT Original amount due at course: 4 Players for $172.00                                 238
Reserved using online booking @ 7:00pm 6/21 EDT Original amount due at course: 4 Players for $172.00                                 235
Reserved using online booking @ 7:00pm 6/20 EDT Original amount due at course: 4 Players for $172.00                                 228
Reserved using online booking @ 7:00pm 6/12 EDT Original amount due at course: 4 Players for $192.00                                 226
                                                                                                                                    ...
Reserved using online booking @ 7:41pm 10/14 EDT Original amount due at course: 2 Players for $86.00 - PAID BOOKING FEE OF $10.00      1
Reserved using online booking @ 8:00pm 10/14 EDT Original amount due at course: 1 Players for $15.00 - PAID BOOKING FEE OF $5.00       1
Reserved using online booking @ 12:32pm 10/15 EDT Original amount due at course: 1 Players for $23.00 - PAID BOOKING FEE OF $5.00      1
Reserved using online booking @ 8:55pm 10/14 EDT                                                                                       1
Reserved using online booking @ 8:45pm 3/13 EST Original amount due at course: 1 Players for $31.00                                    1
Name: count, Length: 463839, dtype: int64

Empty DataFrame
Columns: [tee_time, details, status_text, player_count, tee_sheet, date_cancelled, book_hr, book_min, am_pm, book_month, book_day, cost_per_group, book_yr, booking_time]
Index: []

status_text
deleted       309016
checked in    258379
teed off       35427
NaN            13206
Name: count, dtype: int64

,tee_time,details,status_text,player_count,tee_sheet,date_cancelled,book_hr,book_min,am_pm,book_month,book_day,cost_per_group,book_yr,booking_time
77,2021-03-16 11:00:00,Reserved using online booking @ 9:16pm 3/14 ED...,NaN,4,Bethpage Blue Course,NaT,21,16,pm,3,14,172.00,2021,2021-03-14 21:16:00
78,2021-03-16 12:12:00,Reserved using online booking @ 7:00pm 3/9 EST...,NaN,4,Bethpage Blue Course,NaT,19,0,pm,3,9,172.00,2021,2021-03-09 19:00:00
79,2021-03-16 12:39:00,Reserved using online booking @ 11:59am 3/15 E...,NaN,1,Bethpage Blue Course,NaT,11,59,am,3,15,28.00,2021,2021-03-15 11:59:00
80,2021-03-16 13:15:00,Reserved using online booking @ 7:00pm 3/9 EST...,NaN,4,Bethpage Blue Course,NaT,19,0,pm,3,9,172.00,2021,2021-03-09 19:00:00
81,2021-03-16 13:51:00,Reserved using online booking @ 8:32pm 3/12 ES...,NaN,2,Bethpage Blue Course,NaT,20,32,pm,3,12,56.00,2021,2021-03-12 20:32:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
616026,2025-10-21 13:33:00,Reserved using online booking @ 7:41pm 10/14 E...,NaN,2,Bethpage Red Course,NaT,19,41,pm,10,14,86.00,2025,2025-10-14 19:41:00
616027,2025-10-21 13:42:00,Reserved using online booking @ 8:00pm 10/14 E...,NaN,1,Bethpage Blue Course,NaT,20,0,pm,10,14,15.00,2025,2025-10-14 20:00:00
616028,2025-10-21 13:42:00,Reserved using online booking @ 12:32pm 10/15 ...,NaN,1,Bethpage Blue Course,NaT,24,32,pm,10,15,23.00,2025,2025-10-16 00:32:00
616029,2025-10-21 13:51:00,Reserved using online booking @ 7:02pm 10/14 E...,NaN,4,Bethpage Blue Course,NaT,19,2,pm,10,14,92.00,2025,2025-10-14 19:02:00
616031,2025-10-21 14:00:00,Reserved using online booking @ 8:22am 10/15 E...,NaN,2,Bethpage Blue Course,NaT,8,22,am,10,15,46.00,2025,2025-10-15 08:22:00

player_count
4     218478
1     191046
2     157300
3      49156
8         27
5         13
6          5
54         1
0          1
16         1
Name: count, dtype: int64

Empty DataFrame
Columns: [tee_time, details, status_text, player_count, tee_sheet, date_cancelled, book_hr, book_min, am_pm, book_month, book_day, cost_per_group, book_yr, booking_time]
Index: []

tee_sheet
Bethpage Red Course                 134723
Bethpage Blue Course                112491
Bethpage Green Course                96713
Bethpage Yellow 9 Hole Course        88706
Bethpage Black Course                86363
Bethpage 9 Holes Midday Front 9      59751
Bethpage Early AM 9 Holes Blue       18798
Bethpage Early AM 9 Holes Yellow     18400
Bethpage 9 Holes Midday Back 9          83
Name: count, dtype: int64

Empty DataFrame
Columns: [tee_time, details, status_text, player_count, tee_sheet, date_cancelled, book_hr, book_min, am_pm, book_month, book_day, cost_per_group, book_yr, booking_time]
Index: []

date_cancelled
NaT                           250437
NaN                            57374
July 09, 2021 4:36 AM             18
July 09, 2021 4:35 AM             18
September 24, 2021 7:31 AM        18
                               ...
2025-10-13 20:32:01                1
2025-10-13 20:20:01                1
2025-10-13 20:15:01                1
2025-10-13 21:09:01                1
2025-10-14 12:34:01                1
Name: count, Length: 268147, dtype: int64

,tee_time,details,status_text,player_count,tee_sheet,date_cancelled,book_hr,book_min,am_pm,book_month,book_day,cost_per_group,book_yr,booking_time
0,2021-03-14 07:51:00,Reserved using online booking @ 7:00pm 3/7 EST...,checked in,2,Bethpage Early AM 9 Holes Blue,NaT,19,0,pm,3,7,124.00,2021,2021-03-07 19:00:00
1,2021-03-14 07:51:00,Reserved using online booking @ 9:35pm 3/13 ES...,checked in,1,Bethpage Early AM 9 Holes Blue,NaT,21,35,pm,3,13,31.00,2021,2021-03-13 21:35:00
2,2021-03-14 08:00:00,Reserved using online booking @ 3:32pm 3/13 ES...,checked in,2,Bethpage Early AM 9 Holes Blue,NaT,15,32,pm,3,13,62.00,2021,2021-03-13 15:32:00
3,2021-03-14 08:27:00,Reserved using online booking @ 11:19am 3/13 E...,checked in,4,Bethpage Early AM 9 Holes Blue,NaT,11,19,am,3,13,124.00,2021,2021-03-13 11:19:00
4,2021-03-14 08:36:00,Reserved using online booking @ 5:42pm 3/13 ES...,checked in,1,Bethpage Early AM 9 Holes Blue,NaT,17,42,pm,3,13,93.00,2021,2021-03-13 17:42:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
616026,2025-10-21 13:33:00,Reserved using online booking @ 7:41pm 10/14 E...,NaN,2,Bethpage Red Course,NaT,19,41,pm,10,14,86.00,2025,2025-10-14 19:41:00
616027,2025-10-21 13:42:00,Reserved using online booking @ 8:00pm 10/14 E...,NaN,1,Bethpage Blue Course,NaT,20,0,pm,10,14,15.00,2025,2025-10-14 20:00:00
616028,2025-10-21 13:42:00,Reserved using online booking @ 12:32pm 10/15 ...,NaN,1,Bethpage Blue Course,NaT,24,32,pm,10,15,23.00,2025,2025-10-16 00:32:00
616029,2025-10-21 13:51:00,Reserved using online booking @ 7:02pm 10/14 E...,NaN,4,Bethpage Blue Course,NaT,19,2,pm,10,14,92.00,2025,2025-10-14 19:02:00
616031,2025-10-21 14:00:00,Reserved using online booking @ 8:22am 10/15 E...,NaN,2,Bethpage Blue Course,NaT,8,22,am,10,15,46.00,2025,2025-10-15 08:22:00

book_hr
19    218268
20     38428
21     32151
18     31059
17     25895
22     24277
16     23689
9      22515
10     22182
11     21169
15     20367
24     19377
8      19243
14     19134
13     18495
23     14853
7      14495
6       8834
0       7657
5       4567
1       3448
4       2419
2       1891
3       1615
Name: count, dtype: int64

Empty DataFrame
Columns: [tee_time, details, status_text, player_count, tee_sheet, date_cancelled, book_hr, book_min, am_pm, book_month, book_day, cost_per_group, book_yr, booking_time]
Index: []

book_min
0     125014
1      22170
2      13208
11     11845
10     11772
3      10712
5      10257
4       9863
12      9516
6       9469
13      9081
7       9010
21      8619
8       8476
22      8356
20      8321
14      8279
15      8219
9       8207
16      8135
31      7967
17      7876
23      7807
18      7761
19      7715
24      7709
30      7686
51      7683
41      7634
25      7597
32      7596
27      7544
56      7532
33      7529
42      7481
43      7474
26      7471
28      7459
50      7448
52      7432
29      7391
58      7385
53      7383
57      7354
36      7351
44      7321
59      7320
54      7313
34      7298
55      7288
47      7282
45      7278
38      7222
37      7221
40      7220
35      7190
48      7143
39      7137
49      7016
46      6985
Name: count, dtype: int64

Empty DataFrame
Columns: [tee_time, details, status_text, player_count, tee_sheet, date_cancelled, book_hr, book_min, am_pm, book_month, book_day, cost_per_group, book_yr, booking_time]
Index: []

am_pm
pm    485993
am    130035
Name: count, dtype: int64

Empty DataFrame
Columns: [tee_time, details, status_text, player_count, tee_sheet, date_cancelled, book_hr, book_min, am_pm, book_month, book_day, cost_per_group, book_yr, booking_time]
Index: []

book_month
6     87985
5     87663
7     85117
4     78671
8     75027
10    56053
9     55100
11    36516
3     30717
2      8538
12     8008
1      6633
Name: count, dtype: int64

Empty DataFrame
Columns: [tee_time, details, status_text, player_count, tee_sheet, date_cancelled, book_hr, book_min, am_pm, book_month, book_day, cost_per_group, book_yr, booking_time]
Index: []

book_day
13    21032
14    21014
26    20936
7     20713
25    20379
15    20323
9     20288
8     20278
16    20226
28    20214
11    20208
27    20185
23    20180
21    20149
17    20132
12    20128
10    20094
24    20054
20    19990
22    19979
4     19960
3     19942
29    19907
30    19851
19    19849
1     19841
18    19670
6     19612
2     19527
5     19274
31    12093
Name: count, dtype: int64

Empty DataFrame
Columns: [tee_time, details, status_text, player_count, tee_sheet, date_cancelled, book_hr, book_min, am_pm, book_month, book_day, cost_per_group, book_yr, booking_time]
Index: []

cost_per_group
192.00    69824
172.00    67826
43.00     41386
48.00     41338
86.00     31698
          ...
171.00        1
404.00        1
202.00        1
57.00         1
126.00        1
Name: count, Length: 138, dtype: int64

,tee_time,details,status_text,player_count,tee_sheet,date_cancelled,book_hr,book_min,am_pm,book_month,book_day,cost_per_group,book_yr,booking_time
763,2021-03-23 07:42:00,Reserved using online booking @ 9:31am 3/20 ED...,checked in,1,Bethpage Blue Course,NaT,9,31,am,3,20,NaN,2021,2021-03-20 09:31:00
1270,2021-03-25 17:36:00,Reserved using online booking @ 2:57pm 3/23 ED...,deleted,1,Bethpage Green Course,2021-03-23 13:07:46,14,57,pm,3,23,NaN,2021,2021-03-23 14:57:00
3408,2021-04-06 15:39:00,Reserved using online booking @ 8:17am 4/3 EDT...,deleted,4,Bethpage Yellow 9 Hole Course,2021-04-03 07:01:59,8,17,am,4,3,NaN,2021,2021-04-03 08:17:00
3991,2021-04-08 17:09:00,Reserved using online booking @ 8:59am 4/7 EDT...,checked in,2,Bethpage Yellow 9 Hole Course,NaT,8,59,am,4,7,NaN,2021,2021-04-07 08:59:00
5056,2021-04-14 09:03:00,Reserved using online booking @ 6:15am 4/13 ED...,checked in,1,Bethpage Green Course,NaT,6,15,am,4,13,NaN,2021,2021-04-13 06:15:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615355,2025-10-13 09:03:00,Reserved using online booking @ 7:10pm 10/6 EDT,deleted,4,Bethpage Red Course,2025-10-10 17:24:01,19,10,pm,10,6,NaN,2025,2025-10-06 19:10:00
615632,2025-10-16 09:03:00,Reserved using online booking @ 2:44pm 10/15 E...,checked in,1,Bethpage Early AM 9 Holes Blue,NaT,14,44,pm,10,15,NaN,2025,2025-10-15 14:44:00
615653,2025-10-16 11:45:00,Reserved using online booking @ 7:28pm 10/9 EDT,NaN,2,Bethpage Red Course,NaT,19,28,pm,10,9,NaN,2025,2025-10-09 19:28:00
615966,2025-10-20 13:06:00,Reserved using online booking @ 10:31pm 10/13 EDT,deleted,2,Bethpage Blue Course,2025-10-13 22:56:01,22,31,pm,10,13,NaN,2025,2025-10-13 22:31:00
616030,2025-10-21 14:00:00,Reserved using online booking @ 8:55pm 10/14 EDT,deleted,4,Bethpage Blue Course,2025-10-14 21:21:01,20,55,pm,10,14,NaN,2025,2025-10-14 20:55:00

book_yr
2023    169620
2024    160767
2022    155267
2021     71002
2025     59372
Name: count, dtype: int64

Empty DataFrame
Columns: [tee_time, details, status_text, player_count, tee_sheet, date_cancelled, book_hr, book_min, am_pm, book_month, book_day, cost_per_group, book_yr, booking_time]
Index: []

booking_time
2022-05-21 19:00:00    233
2022-05-22 19:00:00    218
2022-07-10 19:00:00    216
2022-06-26 19:00:00    214
2023-06-09 19:00:00    213
                      ...
2021-03-13 20:37:00      1
2021-03-13 20:26:00      1
2021-03-13 23:18:00      1
2021-03-13 22:55:00      1
2021-03-13 20:40:00      1
Name: count, Length: 372592, dtype: int64

Empty DataFrame
Columns: [tee_time, details, status_text, player_count, tee_sheet, date_cancelled, book_hr, book_min, am_pm, book_month, book_day, cost_per_group, book_yr, booking_time]
Index: []